apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.release.type }}
    app.kubernetes.io/name: {{ include "world-service.name" . }}
    helm.sh/chart: {{ include "world-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    istio: {{ include "world-service.name" . }}
    app: {{ include "world-service.name" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      istio: {{ include "world-service.name" . }}
      app: {{ include "world-service.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        istio: {{ include "world-service.name" . }}
        app: {{ include "world-service.name" . }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        env:
        - name: MESSAGE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.secret.name }}
              key: message
        ports:
        - containerPort: {{ .Values.deployment.port }}
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
