apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.release.type }}
    app.kubernetes.io/name: {{ include "hello-service.name" . }}
    helm.sh/chart: {{ include "hello-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    istio: {{ include "hello-service.name" . }}
    app: {{ include "hello-service.name" . }}
spec:
  selector:
      matchLabels:
        release: {{ .Values.release.type }}
        app.kubernetes.io/name: {{ include "hello-service.name" . }}
        istio: {{ include "hello-service.name" . }}
        app: {{ include "hello-service.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        release: {{ .Values.release.type }}
        app.kubernetes.io/name: {{ include "hello-service.name" . }}
        istio: {{ include "hello-service.name" . }}
        app: {{ include "hello-service.name" . }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.deployment.image }}
          env:
          - name: WORLD_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-{{ .Values.configMap.name }}
                key: world_service_address
          - name: MESSAGE
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-{{ .Values.secret.name }}
                key: message
          ports:
            - containerPort: {{ .Values.deployment.port }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
